name: VS Code Extension Actions

on:
    pull_request:
        paths:
            - "extension/**"

jobs:
    build:
        runs-on: ubuntu-latest
        name: Bundle with webpack

        steps:
            - uses: actions/checkout@v2
            - working-directory: extension
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm ci
            - run: npm build

    test:
        runs-on: ubuntu-latest
        name: Run tests

        steps:
            - uses: actions/checkout@v2
            - working-directory: extension
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm ci
            - run: npm test

    prettier:
        runs-on: ubuntu-latest
        name: Run Prettier
        needs: build

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - working-directory: extension
            - name: Prettify
              uses: creyD/prettier_action@v3.3
              with:
                  prettier_options: --write **/*.{js,ts,md,json}
                  only_changed: True
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
